/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package objetos.Mensajeria;

/**
 *
 * @author MAURO DI
 * 
 * ESTA INTERFACE GENERA Y ADMINISTRA LOS PENDIENTES DE CAMBIOS EN LOS PEDIDOS
 * UN PEDIDO UNA VEZ MODIFICADO Y CON UNA RUTA DE DESTINO CERRADA QUEDA PENDIENTE HASTA SU APROBACION POR EL ADMINISTRADOR
 * PARA ESO SE CARGAN LOS DATOS EN LA TABLA PENDIENTES CON EL FIN DE DEJARLOS EN ESTADO LATENTE HASTA QUE EL ADMINISTRADOR DECIDA SI 
 * SE ABRE O NO LA RUTA ASIGNADA A TAL FIN
 * 
 * - EN EL CASO DE APERTURA DE LA MISMA EL SISTEMA GENERA UN UPDATE DE LA INFORMACION DE LA PEDIDOS_CARGA1 CAMBIANDO LOS VALORES EN EL PEDIDO
 * PARA QUE EL MISMO PASE A LA FECHA NUEVA O A LA RUTA CERRADA
 * 
 * - EN EL CASO DE SER RECHAZADA LA APERTURA DE LA RUTA, LA MISMA NO GENERARA CONSECUENCIAS EN EL PEDIDO SIENDO NECESARIO PASAR EL MISMO A UNA 
 * FECHA CON RUTA DE DESTINO ABIERTA O CORRECTA
 * 
 * EL MENSAJE RECIBIDO POR EL ADMINISTRADOR IMPULSA A TOMAR UNA ACCION PARA EL PEDIDO PENDIENTE O EL MENSAJE RECIBIDO:
 * 
 *  - SI ES ACEPTADO EL PEDIDO, RETORNA UN MENSAJE AL OPERADOR INFORMANDO QUE EL PEDIDO ESTA CARGADO PARA AL RUTA Y FECHA MODIFICADA
 *  - SI ES RECHAZADO EL PEDIDO DE IGUAL FORMA RETORNA UN MENSAJE INFORMANDO LA NECESIDAD DE MODIFICAR LA FECHA DE ENVIO DADO EL RECHAZO
 * 
 * EL BOOLEANO VA A SER TRUE SI SE GUARDO CORRECTAMENTE LOS DATOS
 * EN CASO DE SER FALSE NO VA A GUARDAR NADA, SIGNIFICA QUE NO SE PUDO COMPLETAR LA OPERACION
 * 
 * DATOS A GUARDAR EN TABLA:
 * 
 *  - NUMERODEPEDIDO: STRING CORRESPONDIENTE AL NUMERO DE PEDIDO DE TANGO
 *  - FECHAVIEJA: STRING CON LA FECHA DE ENTREGA PASADA EN PRINCIPIO
 *  - FECHANUEVA:STRING CON LA FECHA NUEVA PARA EL ENVIO
 *  - NUEVARUTA:INTEGER CON EL NUMERO DE LA NUEVA RUTA ASIGNADA
 *  - TIPORESPUESTA :INTEGER DONDE 6 ES RUTA CERRADA, 7 RUTA ABIERTA (ESTOS TIPOS SE ENCUENTRAN EN LA TABLA MENSAJESTIPOS), SI BIEN NO HA SIDO PASADO
 * EL TIPO DE RESPUESTA EL MISMO ESTA COMO PREDETERMINADO EL 6 COMO PREDEFINIDO
 * 
 * VALORES IDENTIFICATORIOS DE LOS VALORES PENDIENTES:
 *  NUMERODEPEDIDO:STRING
 *  FECHAVIEJA:STRING
 * 
 * 
 * 
 */
public interface Corregible {
    public Boolean DejarPendiente(String numeroPedido,String fechaVieja,String fechaNueva,int nuevaRuta);//DEVUELVE TRUE SI GUARDO COMO PENDIENTE O FLASE SI NO PUDO
    public Boolean ConsultarCondicion(String numeroDePedido,String fechaVieja);//DEVUELVE TRUE SI LA RUTA ESTA ABIERTA(FUE ACEPTADA SU APERTURA) FALSE SI SE RECHAZO
    public Boolean AceptarAperturaRuta(String numeroDePedido,String fechaVieja,String fechaNueva);//DEVUELVE TRUE SI SE PUDO ABRIR LA RUTA, FALSE SI NO SE PUDO
    public Boolean RechazarAperturaRuta(String numeroDePedido,String fechaVieja,String fechaNueva);//DEVUELVE TRUE SI SE PUDO GRABAR EL RECHAZO O FLASE SI NO
    public Boolean ValidarCoincidencia(String numeroDePedido,String fechaNueva,int nuevaRuta);//CHEQUEA QUE AL MODIFICAR SOLAMENTE LA FECHA DE ENTREGA NO SE PASE CON 
    //UNA RUTA DE DESTINO QUE NO CORRESPONDE, DEVUELVE TRUE SI LA RUTA DE DESTINO ES COINCIDENTE CON LA FECHA NUEVA PASADA - FALSE SI NO LO ES
    public Object ModificarCantidad(Object pedido,Double nuevaCantidad);
    public Object ModificarFechaEnvioItem(Object pedido,String fechaEnvio);
    public Object ModificarCantidadPendiente(Object pedido,Double nuevaCantidadPendiente);
    public Object ModificarRutaDeEnvio(Object pedido,int numeroRuta);
    //public Boolean 
    
}
