/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ModificacionDePedidos.java
 *
 * Created on 03-feb-2012, 12:01:39
 */
package interfaces.clientes;

import interfaces.clientes.tablas.miTablaModificacion;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import objetos.PedidosParaReparto;
import proceso.Procesos;
//import siderconcapadatos.tablas.miTablaModificacion;

/**
 *
 * @author Administrador
 */
public class ModificacionDePedidos extends javax.swing.JInternalFrame {

    /** Creates new form ModificacionDePedidos */
    static ArrayList listadoDelPedido;
    static String nmPedido;
    static PedidosParaReparto pedido;

    public static void setPedido(PedidosParaReparto pedido) {
        ModificacionDePedidos.pedido = pedido;
    }

    public static void setNmPedido(String nmPedido) {
        ModificacionDePedidos.nmPedido = nmPedido;
    }
    
    public ModificacionDePedidos(PedidosParaReparto pedido) {
        ModificacionDePedidos.pedido = pedido;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        miTablaModificacion mod=new miTablaModificacion();
        PedidosParaReparto pedid=new PedidosParaReparto();
        System.out.println("numero de pedido "+pedido.getCodigoTangoDePedido());
        Procesos pro=new Procesos();
        ArrayList listado=new ArrayList();
        try{
            listado=pro.detallePedidoParaCorreccion(pedido.getCodigoTangoDePedido(),pedido.getFechaEnvio());
            listadoDelPedido=listado;
            //System.out.println("Pedido NUMERO :"+ListadoDePedidosParaReparto.numeroDePedido+"fehca "+ListadoDePedidosParaReparto.fechaPedido);
        }catch(Exception ex){
            System.out.println("no se cargo el detalle "+ex);
        }
        Iterator ii=listado.listIterator();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visualizacion de Pedidos");
        setVisible(true);

        jTable1.setModel(mod);
        mod.addColumn("Nro Pedido");
        mod.addColumn("Cod Articulo");
        mod.addColumn("descrip Articulo");
        mod.addColumn("cant a enviar");
        mod.addColumn("cant s/fecha");
        mod.addColumn("fecha de entrega");
        //mod.addColumn("eliminar Item");
        Object[] fila=new Object[6];
        while(ii.hasNext()){
            pedid=(PedidosParaReparto)ii.next();
            fila[0]=pedid.getCodigoTangoDePedido();
            fila[1]=pedid.getCodigoArticulo();
            fila[2]=pedid.getDescripcionArticulo();
            fila[3]=pedid.getCantidadArticulo();
            fila[4]=pedid.getCantidadArticuloPendiente();
            fila[5]=pedid.getFechaEnvio();
            //fila[6]=false;
            mod.addRow(fila);
        }
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
